create table Person(
                       person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(200) NOT NULL UNIQUE,
                       year_of_birth INT NOT NULL
);

create table Book(
                     book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     person_id INT REFERENCES Person(person_id) ON DELETE SET NULL,
                     name varchar(200) NOT NULL,
                     author varchar(200) NOT NULL,
                     year INT NOT NULL
);

INSERT INTO Person(full_name, year_of_birth)
VALUES ('Яромич Зефир Котович', 2020),
       ('Яромич Анастасия Викторовна', 1995),
       ('Яромич Афина Котяковна', 2020),
       ('Яромич Евгений Вячеславоч', 1993),
       ('Яромич Пушинка Котяковна', 2010);


INSERT INTO Book(name, author, year)
VALUES ('Над пропастью во ржи', 'Джером Сэлинджер', 1951),
       ('День опричника', 'Владимир Сорокин', 2006),
       ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018),
       ('Философия Java', 'Брюс Эккель', 2018),
       ('Психопаталогия обыденной жизни', 'Фрейд Зигмунд', 1904),
       ('Игра в бисер', 'Герман Гессе', 1943),
       ('Бытие и время', 'Мартин Хайдеггер', 1927);